Support more placement options in TooltipTypes.d.ts
ReactTooltip/react-tooltip pull request #1047
Opened 2023-06-23 19:09 UTC by colynfulcrum

Support more place types that floating-ui supports. These actually already work but I need the type to be updated to reflect existing allowed types.

2023-06-23 19:25 UTC, gabrieljablonski requested changes

2023-06-23 19:25 UTC, gabrieljablonski commented on src/components/Tooltip/TooltipTypes.d.ts
> +  | "left-end";
```suggestion
export type PlacesType =
  | 'top'
  | 'right'
  | 'bottom'
  | 'left'
  | 'top-start'
  | 'top-end'
  | 'right-start'
  | 'right-end'
  | 'bottom-start'
  | 'bottom-end'
  | 'left-start'
  | 'left-end'
```

2023-06-23 19:27 UTC, gabrieljablonski requested changes

2023-06-23 19:27 UTC, gabrieljablonski commented on src/components/Tooltip/TooltipTypes.d.ts
> +  | "left-end";
just to be consistent with `floating-ui`

```suggestion
export type PlacesType =
  | 'top'
  | 'top-start'
  | 'top-end'
  | 'right'
  | 'right-start'
  | 'right-end'
  | 'bottom'
  | 'bottom-start'
  | 'bottom-end'
  | 'left'
  | 'left-start'
  | 'left-end'
```

2023-06-23 19:37 UTC, gabrieljablonski commented
Thanks for suggesting this. Before we can merge this, we have to update a few more files.

Source:
- `src/utils/compute-positions-types.d.ts`
Docs:
- `docs/options.mdx`
- `docs/examples/place.mdx`

I believe I haven't missed any. Feel free to update them, or leave it to us for whenever we get the time.

2023-06-23 22:01 UTC, colynfulcrum commented
> Thanks for suggesting this. Before we can merge this, we have to update a few more files.
> 
> Source:
> 
> * `src/utils/compute-positions-types.d.ts`
> 
> Docs:
> 
> * `docs/options.mdx`
> * `docs/examples/place.mdx`
> 
> I believe I haven't missed any. Feel free to update them, or leave it to us for whenever we get the time.

I've updated those files. Hope that works. Have a great weekend!

2023-06-23 22:07 UTC, colynfulcrum commented
@gabrieljablonski sorry, I missed a big section in the docs. I will get to this later tonight.

<img width="1026" alt="image" src="https://github.com/ReactTooltip/react-tooltip/assets/122113864/0defa926-4acb-4cdd-b5af-c65beefe99f3">

2023-06-24 13:45 UTC, colynfulcrum commented
@gabrieljablonski I updated the examples to include the other types... see screen recording

https://github.com/ReactTooltip/react-tooltip/assets/122113864/93c0de89-ed45-49de-a518-1d3e03775bc9

2023-06-24 16:06 UTC, gabrieljablonski approved these changes

2023-06-26 21:11 UTC, danielbarion approved these changes

2023-06-27 13:20 UTC, merged

2023-06-27 13:23 UTC, danielbarion commented
Available at `v5.15.1`