fix: update node contains conditional check on Tooltip component
ReactTooltip/react-tooltip pull request #988
Opened 2023-03-22 13:13 UTC by danielbarion

closes #985

2023-03-22 13:20 UTC, gabrieljablonski requested changes

2023-03-22 13:20 UTC, gabrieljablonski commented on src/components/Tooltip/Tooltip.tsx
> +            if (node?.contains && node.contains(activeAnchor)) {
```suggestion
            if (node?.contains?.(activeAnchor)) {
```

2023-03-22 13:25 UTC, gabrieljablonski commented
I have no problem with doing this change but it feels unnecessary. `mutation.removedNodes` should never have a `null` node inside it, and if a node is not `null`, it will always have the `contains()` method defined.

Maybe in older browsers something weird might happen? Or maybe if the reference to the node becomes stale `contains` becomes `null`?

Again, we can do the change just in case, but if #985 wasn't just a suggestion, and @rolandpoulter actually run into an error because of this, I'd love to see a reproducible example purely out of curiosity.

2023-03-22 13:30 UTC, danielbarion commented
@gabrieljablonski I do agree with you, can you handle this PR and this issue, please?

2023-03-22 21:05 UTC, rolandpoulter commented
@gabrieljablonski I can look into the reason why, but I did get an error after upgrading to the latest version. I patched it in my node_modules with the above change because I noticed in the code you are checking for node to be truthy before calling contains elsewhere. There might be something on my end with how I wrapped the tooltip that causes this issue but it will take some time to investigate and provide the exact reproduction.

2023-03-22 21:14 UTC, gabrieljablonski commented
> @gabrieljablonski I can look into the reason why, but I did get an error after upgrading to the latest version. I patched it in my node_modules with the above change because I noticed in the code you are checking for node to be truthy before calling contains elsewhere. There might be something on my end with how I wrapped the tooltip that causes this issue but it will take some time to investigate and provide the exact reproduction.

@rolandpoulter No worries, just wanted to make sure this was what solved your problem. We'll merge this change and release a new version soon.

Thanks for reporting it!

2023-03-23 01:32 UTC, gabrieljablonski approved these changes

2023-03-23 01:33 UTC, merged